//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCIONES
    {
        public int ID_DIRECCION { get; set; }
        public int ID_PROVINCIA { get; set; }
        public int ID_CANTON { get; set; }
        public string DIRECCION { get; set; }
        public string CODIGO_POSTAL { get; set; }
    
        public virtual CANTONES CANTONES { get; set; }
        public virtual PROVINCIAS PROVINCIAS { get; set; }
    }
}
