//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_VENTA { get; set; }
        public Nullable<System.DateTime> FECHA_VENTA { get; set; }
        public int CANTIDAD { get; set; }
        public int PRECIO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_USUARIO { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
